// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sistema_arquivos.proto
// Protobuf C++ Version: 6.31.1

#ifndef sistema_5farquivos_2eproto_2epb_2eh
#define sistema_5farquivos_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_sistema_5farquivos_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_sistema_5farquivos_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_sistema_5farquivos_2eproto;
}  // extern "C"
namespace sistemaarquivos {
class AbreReply;
struct AbreReplyDefaultTypeInternal;
extern AbreReplyDefaultTypeInternal _AbreReply_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull AbreReply_class_data_;
class AbreRequest;
struct AbreRequestDefaultTypeInternal;
extern AbreRequestDefaultTypeInternal _AbreRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull AbreRequest_class_data_;
class EscreveReply;
struct EscreveReplyDefaultTypeInternal;
extern EscreveReplyDefaultTypeInternal _EscreveReply_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull EscreveReply_class_data_;
class EscreveRequest;
struct EscreveRequestDefaultTypeInternal;
extern EscreveRequestDefaultTypeInternal _EscreveRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull EscreveRequest_class_data_;
class FechaReply;
struct FechaReplyDefaultTypeInternal;
extern FechaReplyDefaultTypeInternal _FechaReply_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull FechaReply_class_data_;
class FechaRequest;
struct FechaRequestDefaultTypeInternal;
extern FechaRequestDefaultTypeInternal _FechaRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull FechaRequest_class_data_;
class LeReply;
struct LeReplyDefaultTypeInternal;
extern LeReplyDefaultTypeInternal _LeReply_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull LeReply_class_data_;
class LeRequest;
struct LeRequestDefaultTypeInternal;
extern LeRequestDefaultTypeInternal _LeRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull LeRequest_class_data_;
}  // namespace sistemaarquivos
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace sistemaarquivos {

// ===================================================================


// -------------------------------------------------------------------

class LeRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:sistemaarquivos.LeRequest) */ {
 public:
  inline LeRequest() : LeRequest(nullptr) {}
  ~LeRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(LeRequest* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(LeRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR LeRequest(::google::protobuf::internal::ConstantInitialized);

  inline LeRequest(const LeRequest& from) : LeRequest(nullptr, from) {}
  inline LeRequest(LeRequest&& from) noexcept
      : LeRequest(nullptr, ::std::move(from)) {}
  inline LeRequest& operator=(const LeRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline LeRequest& operator=(LeRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LeRequest& default_instance() {
    return *reinterpret_cast<const LeRequest*>(
        &_LeRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(LeRequest& a, LeRequest& b) { a.Swap(&b); }
  inline void Swap(LeRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LeRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LeRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<LeRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LeRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const LeRequest& from) { LeRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(LeRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "sistemaarquivos.LeRequest"; }

 protected:
  explicit LeRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  LeRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const LeRequest& from);
  LeRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, LeRequest&& from) noexcept
      : LeRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDescritorFieldNumber = 1,
    kPosicaoFieldNumber = 2,
    kTamanhoFieldNumber = 3,
  };
  // int32 descritor = 1;
  void clear_descritor() ;
  ::int32_t descritor() const;
  void set_descritor(::int32_t value);

  private:
  ::int32_t _internal_descritor() const;
  void _internal_set_descritor(::int32_t value);

  public:
  // int32 posicao = 2;
  void clear_posicao() ;
  ::int32_t posicao() const;
  void set_posicao(::int32_t value);

  private:
  ::int32_t _internal_posicao() const;
  void _internal_set_posicao(::int32_t value);

  public:
  // int32 tamanho = 3;
  void clear_tamanho() ;
  ::int32_t tamanho() const;
  void set_tamanho(::int32_t value);

  private:
  ::int32_t _internal_tamanho() const;
  void _internal_set_tamanho(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:sistemaarquivos.LeRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const LeRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t descritor_;
    ::int32_t posicao_;
    ::int32_t tamanho_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sistema_5farquivos_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull LeRequest_class_data_;
// -------------------------------------------------------------------

class LeReply final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:sistemaarquivos.LeReply) */ {
 public:
  inline LeReply() : LeReply(nullptr) {}
  ~LeReply() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(LeReply* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(LeReply));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR LeReply(::google::protobuf::internal::ConstantInitialized);

  inline LeReply(const LeReply& from) : LeReply(nullptr, from) {}
  inline LeReply(LeReply&& from) noexcept
      : LeReply(nullptr, ::std::move(from)) {}
  inline LeReply& operator=(const LeReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline LeReply& operator=(LeReply&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LeReply& default_instance() {
    return *reinterpret_cast<const LeReply*>(
        &_LeReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(LeReply& a, LeReply& b) { a.Swap(&b); }
  inline void Swap(LeReply* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LeReply* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LeReply* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<LeReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LeReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const LeReply& from) { LeReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(LeReply* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "sistemaarquivos.LeReply"; }

 protected:
  explicit LeReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  LeReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const LeReply& from);
  LeReply(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, LeReply&& from) noexcept
      : LeReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kConteudoLerFieldNumber = 2,
    kStatusFieldNumber = 1,
  };
  // bytes conteudo_ler = 2;
  void clear_conteudo_ler() ;
  const ::std::string& conteudo_ler() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_conteudo_ler(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_conteudo_ler();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_conteudo_ler();
  void set_allocated_conteudo_ler(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_conteudo_ler() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_conteudo_ler(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_conteudo_ler();

  public:
  // int32 status = 1;
  void clear_status() ;
  ::int32_t status() const;
  void set_status(::int32_t value);

  private:
  ::int32_t _internal_status() const;
  void _internal_set_status(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:sistemaarquivos.LeReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const LeReply& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr conteudo_ler_;
    ::int32_t status_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sistema_5farquivos_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull LeReply_class_data_;
// -------------------------------------------------------------------

class FechaRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:sistemaarquivos.FechaRequest) */ {
 public:
  inline FechaRequest() : FechaRequest(nullptr) {}
  ~FechaRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FechaRequest* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FechaRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FechaRequest(::google::protobuf::internal::ConstantInitialized);

  inline FechaRequest(const FechaRequest& from) : FechaRequest(nullptr, from) {}
  inline FechaRequest(FechaRequest&& from) noexcept
      : FechaRequest(nullptr, ::std::move(from)) {}
  inline FechaRequest& operator=(const FechaRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline FechaRequest& operator=(FechaRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FechaRequest& default_instance() {
    return *reinterpret_cast<const FechaRequest*>(
        &_FechaRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 6;
  friend void swap(FechaRequest& a, FechaRequest& b) { a.Swap(&b); }
  inline void Swap(FechaRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FechaRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FechaRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<FechaRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FechaRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FechaRequest& from) { FechaRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FechaRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "sistemaarquivos.FechaRequest"; }

 protected:
  explicit FechaRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  FechaRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FechaRequest& from);
  FechaRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, FechaRequest&& from) noexcept
      : FechaRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDescritorFieldNumber = 1,
  };
  // int32 descritor = 1;
  void clear_descritor() ;
  ::int32_t descritor() const;
  void set_descritor(::int32_t value);

  private:
  ::int32_t _internal_descritor() const;
  void _internal_set_descritor(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:sistemaarquivos.FechaRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const FechaRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t descritor_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sistema_5farquivos_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull FechaRequest_class_data_;
// -------------------------------------------------------------------

class FechaReply final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:sistemaarquivos.FechaReply) */ {
 public:
  inline FechaReply() : FechaReply(nullptr) {}
  ~FechaReply() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FechaReply* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FechaReply));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FechaReply(::google::protobuf::internal::ConstantInitialized);

  inline FechaReply(const FechaReply& from) : FechaReply(nullptr, from) {}
  inline FechaReply(FechaReply&& from) noexcept
      : FechaReply(nullptr, ::std::move(from)) {}
  inline FechaReply& operator=(const FechaReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline FechaReply& operator=(FechaReply&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FechaReply& default_instance() {
    return *reinterpret_cast<const FechaReply*>(
        &_FechaReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 7;
  friend void swap(FechaReply& a, FechaReply& b) { a.Swap(&b); }
  inline void Swap(FechaReply* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FechaReply* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FechaReply* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<FechaReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FechaReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FechaReply& from) { FechaReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FechaReply* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "sistemaarquivos.FechaReply"; }

 protected:
  explicit FechaReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  FechaReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FechaReply& from);
  FechaReply(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, FechaReply&& from) noexcept
      : FechaReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStatusFieldNumber = 1,
  };
  // int32 status = 1;
  void clear_status() ;
  ::int32_t status() const;
  void set_status(::int32_t value);

  private:
  ::int32_t _internal_status() const;
  void _internal_set_status(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:sistemaarquivos.FechaReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const FechaReply& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t status_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sistema_5farquivos_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull FechaReply_class_data_;
// -------------------------------------------------------------------

class EscreveRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:sistemaarquivos.EscreveRequest) */ {
 public:
  inline EscreveRequest() : EscreveRequest(nullptr) {}
  ~EscreveRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(EscreveRequest* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(EscreveRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR EscreveRequest(::google::protobuf::internal::ConstantInitialized);

  inline EscreveRequest(const EscreveRequest& from) : EscreveRequest(nullptr, from) {}
  inline EscreveRequest(EscreveRequest&& from) noexcept
      : EscreveRequest(nullptr, ::std::move(from)) {}
  inline EscreveRequest& operator=(const EscreveRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline EscreveRequest& operator=(EscreveRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EscreveRequest& default_instance() {
    return *reinterpret_cast<const EscreveRequest*>(
        &_EscreveRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(EscreveRequest& a, EscreveRequest& b) { a.Swap(&b); }
  inline void Swap(EscreveRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EscreveRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EscreveRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<EscreveRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const EscreveRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const EscreveRequest& from) { EscreveRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(EscreveRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "sistemaarquivos.EscreveRequest"; }

 protected:
  explicit EscreveRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  EscreveRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const EscreveRequest& from);
  EscreveRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, EscreveRequest&& from) noexcept
      : EscreveRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kConteudoEscreverFieldNumber = 3,
    kDescritorFieldNumber = 1,
    kPosicaoFieldNumber = 2,
  };
  // bytes conteudo_escrever = 3;
  void clear_conteudo_escrever() ;
  const ::std::string& conteudo_escrever() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_conteudo_escrever(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_conteudo_escrever();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_conteudo_escrever();
  void set_allocated_conteudo_escrever(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_conteudo_escrever() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_conteudo_escrever(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_conteudo_escrever();

  public:
  // int32 descritor = 1;
  void clear_descritor() ;
  ::int32_t descritor() const;
  void set_descritor(::int32_t value);

  private:
  ::int32_t _internal_descritor() const;
  void _internal_set_descritor(::int32_t value);

  public:
  // int32 posicao = 2;
  void clear_posicao() ;
  ::int32_t posicao() const;
  void set_posicao(::int32_t value);

  private:
  ::int32_t _internal_posicao() const;
  void _internal_set_posicao(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:sistemaarquivos.EscreveRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const EscreveRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr conteudo_escrever_;
    ::int32_t descritor_;
    ::int32_t posicao_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sistema_5farquivos_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull EscreveRequest_class_data_;
// -------------------------------------------------------------------

class EscreveReply final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:sistemaarquivos.EscreveReply) */ {
 public:
  inline EscreveReply() : EscreveReply(nullptr) {}
  ~EscreveReply() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(EscreveReply* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(EscreveReply));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR EscreveReply(::google::protobuf::internal::ConstantInitialized);

  inline EscreveReply(const EscreveReply& from) : EscreveReply(nullptr, from) {}
  inline EscreveReply(EscreveReply&& from) noexcept
      : EscreveReply(nullptr, ::std::move(from)) {}
  inline EscreveReply& operator=(const EscreveReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline EscreveReply& operator=(EscreveReply&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EscreveReply& default_instance() {
    return *reinterpret_cast<const EscreveReply*>(
        &_EscreveReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(EscreveReply& a, EscreveReply& b) { a.Swap(&b); }
  inline void Swap(EscreveReply* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EscreveReply* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EscreveReply* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<EscreveReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const EscreveReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const EscreveReply& from) { EscreveReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(EscreveReply* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "sistemaarquivos.EscreveReply"; }

 protected:
  explicit EscreveReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  EscreveReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const EscreveReply& from);
  EscreveReply(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, EscreveReply&& from) noexcept
      : EscreveReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStatusFieldNumber = 1,
    kBytesEscritosFieldNumber = 2,
  };
  // int32 status = 1;
  void clear_status() ;
  ::int32_t status() const;
  void set_status(::int32_t value);

  private:
  ::int32_t _internal_status() const;
  void _internal_set_status(::int32_t value);

  public:
  // int32 bytes_escritos = 2;
  void clear_bytes_escritos() ;
  ::int32_t bytes_escritos() const;
  void set_bytes_escritos(::int32_t value);

  private:
  ::int32_t _internal_bytes_escritos() const;
  void _internal_set_bytes_escritos(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:sistemaarquivos.EscreveReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const EscreveReply& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t status_;
    ::int32_t bytes_escritos_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sistema_5farquivos_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull EscreveReply_class_data_;
// -------------------------------------------------------------------

class AbreRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:sistemaarquivos.AbreRequest) */ {
 public:
  inline AbreRequest() : AbreRequest(nullptr) {}
  ~AbreRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AbreRequest* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AbreRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AbreRequest(::google::protobuf::internal::ConstantInitialized);

  inline AbreRequest(const AbreRequest& from) : AbreRequest(nullptr, from) {}
  inline AbreRequest(AbreRequest&& from) noexcept
      : AbreRequest(nullptr, ::std::move(from)) {}
  inline AbreRequest& operator=(const AbreRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AbreRequest& operator=(AbreRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AbreRequest& default_instance() {
    return *reinterpret_cast<const AbreRequest*>(
        &_AbreRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(AbreRequest& a, AbreRequest& b) { a.Swap(&b); }
  inline void Swap(AbreRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AbreRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AbreRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AbreRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AbreRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AbreRequest& from) { AbreRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AbreRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "sistemaarquivos.AbreRequest"; }

 protected:
  explicit AbreRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AbreRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AbreRequest& from);
  AbreRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AbreRequest&& from) noexcept
      : AbreRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNomeArquivoFieldNumber = 1,
  };
  // string nome_arquivo = 1;
  void clear_nome_arquivo() ;
  const ::std::string& nome_arquivo() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_nome_arquivo(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_nome_arquivo();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_nome_arquivo();
  void set_allocated_nome_arquivo(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_nome_arquivo() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_nome_arquivo(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_nome_arquivo();

  public:
  // @@protoc_insertion_point(class_scope:sistemaarquivos.AbreRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 48,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AbreRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr nome_arquivo_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sistema_5farquivos_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull AbreRequest_class_data_;
// -------------------------------------------------------------------

class AbreReply final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:sistemaarquivos.AbreReply) */ {
 public:
  inline AbreReply() : AbreReply(nullptr) {}
  ~AbreReply() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AbreReply* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AbreReply));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AbreReply(::google::protobuf::internal::ConstantInitialized);

  inline AbreReply(const AbreReply& from) : AbreReply(nullptr, from) {}
  inline AbreReply(AbreReply&& from) noexcept
      : AbreReply(nullptr, ::std::move(from)) {}
  inline AbreReply& operator=(const AbreReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline AbreReply& operator=(AbreReply&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AbreReply& default_instance() {
    return *reinterpret_cast<const AbreReply*>(
        &_AbreReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(AbreReply& a, AbreReply& b) { a.Swap(&b); }
  inline void Swap(AbreReply* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AbreReply* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AbreReply* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AbreReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AbreReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AbreReply& from) { AbreReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AbreReply* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "sistemaarquivos.AbreReply"; }

 protected:
  explicit AbreReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AbreReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AbreReply& from);
  AbreReply(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AbreReply&& from) noexcept
      : AbreReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStatusFieldNumber = 1,
    kDescritorFieldNumber = 2,
  };
  // int32 status = 1;
  void clear_status() ;
  ::int32_t status() const;
  void set_status(::int32_t value);

  private:
  ::int32_t _internal_status() const;
  void _internal_set_status(::int32_t value);

  public:
  // int32 descritor = 2;
  void clear_descritor() ;
  ::int32_t descritor() const;
  void set_descritor(::int32_t value);

  private:
  ::int32_t _internal_descritor() const;
  void _internal_set_descritor(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:sistemaarquivos.AbreReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AbreReply& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t status_;
    ::int32_t descritor_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sistema_5farquivos_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull AbreReply_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AbreRequest

// string nome_arquivo = 1;
inline void AbreRequest::clear_nome_arquivo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nome_arquivo_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& AbreRequest::nome_arquivo() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:sistemaarquivos.AbreRequest.nome_arquivo)
  return _internal_nome_arquivo();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void AbreRequest::set_nome_arquivo(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.nome_arquivo_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:sistemaarquivos.AbreRequest.nome_arquivo)
}
inline ::std::string* PROTOBUF_NONNULL AbreRequest::mutable_nome_arquivo()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_nome_arquivo();
  // @@protoc_insertion_point(field_mutable:sistemaarquivos.AbreRequest.nome_arquivo)
  return _s;
}
inline const ::std::string& AbreRequest::_internal_nome_arquivo() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nome_arquivo_.Get();
}
inline void AbreRequest::_internal_set_nome_arquivo(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.nome_arquivo_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL AbreRequest::_internal_mutable_nome_arquivo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.nome_arquivo_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE AbreRequest::release_nome_arquivo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:sistemaarquivos.AbreRequest.nome_arquivo)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.nome_arquivo_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.nome_arquivo_.Set("", GetArena());
  }
  return released;
}
inline void AbreRequest::set_allocated_nome_arquivo(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.nome_arquivo_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.nome_arquivo_.IsDefault()) {
    _impl_.nome_arquivo_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:sistemaarquivos.AbreRequest.nome_arquivo)
}

// -------------------------------------------------------------------

// AbreReply

// int32 status = 1;
inline void AbreReply::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t AbreReply::status() const {
  // @@protoc_insertion_point(field_get:sistemaarquivos.AbreReply.status)
  return _internal_status();
}
inline void AbreReply::set_status(::int32_t value) {
  _internal_set_status(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:sistemaarquivos.AbreReply.status)
}
inline ::int32_t AbreReply::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.status_;
}
inline void AbreReply::_internal_set_status(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

// int32 descritor = 2;
inline void AbreReply::clear_descritor() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.descritor_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t AbreReply::descritor() const {
  // @@protoc_insertion_point(field_get:sistemaarquivos.AbreReply.descritor)
  return _internal_descritor();
}
inline void AbreReply::set_descritor(::int32_t value) {
  _internal_set_descritor(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:sistemaarquivos.AbreReply.descritor)
}
inline ::int32_t AbreReply::_internal_descritor() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.descritor_;
}
inline void AbreReply::_internal_set_descritor(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.descritor_ = value;
}

// -------------------------------------------------------------------

// LeRequest

// int32 descritor = 1;
inline void LeRequest::clear_descritor() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.descritor_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t LeRequest::descritor() const {
  // @@protoc_insertion_point(field_get:sistemaarquivos.LeRequest.descritor)
  return _internal_descritor();
}
inline void LeRequest::set_descritor(::int32_t value) {
  _internal_set_descritor(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:sistemaarquivos.LeRequest.descritor)
}
inline ::int32_t LeRequest::_internal_descritor() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.descritor_;
}
inline void LeRequest::_internal_set_descritor(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.descritor_ = value;
}

// int32 posicao = 2;
inline void LeRequest::clear_posicao() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.posicao_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t LeRequest::posicao() const {
  // @@protoc_insertion_point(field_get:sistemaarquivos.LeRequest.posicao)
  return _internal_posicao();
}
inline void LeRequest::set_posicao(::int32_t value) {
  _internal_set_posicao(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:sistemaarquivos.LeRequest.posicao)
}
inline ::int32_t LeRequest::_internal_posicao() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.posicao_;
}
inline void LeRequest::_internal_set_posicao(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.posicao_ = value;
}

// int32 tamanho = 3;
inline void LeRequest::clear_tamanho() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tamanho_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t LeRequest::tamanho() const {
  // @@protoc_insertion_point(field_get:sistemaarquivos.LeRequest.tamanho)
  return _internal_tamanho();
}
inline void LeRequest::set_tamanho(::int32_t value) {
  _internal_set_tamanho(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:sistemaarquivos.LeRequest.tamanho)
}
inline ::int32_t LeRequest::_internal_tamanho() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tamanho_;
}
inline void LeRequest::_internal_set_tamanho(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tamanho_ = value;
}

// -------------------------------------------------------------------

// LeReply

// int32 status = 1;
inline void LeReply::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t LeReply::status() const {
  // @@protoc_insertion_point(field_get:sistemaarquivos.LeReply.status)
  return _internal_status();
}
inline void LeReply::set_status(::int32_t value) {
  _internal_set_status(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:sistemaarquivos.LeReply.status)
}
inline ::int32_t LeReply::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.status_;
}
inline void LeReply::_internal_set_status(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

// bytes conteudo_ler = 2;
inline void LeReply::clear_conteudo_ler() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.conteudo_ler_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& LeReply::conteudo_ler() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:sistemaarquivos.LeReply.conteudo_ler)
  return _internal_conteudo_ler();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void LeReply::set_conteudo_ler(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.conteudo_ler_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:sistemaarquivos.LeReply.conteudo_ler)
}
inline ::std::string* PROTOBUF_NONNULL LeReply::mutable_conteudo_ler()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_conteudo_ler();
  // @@protoc_insertion_point(field_mutable:sistemaarquivos.LeReply.conteudo_ler)
  return _s;
}
inline const ::std::string& LeReply::_internal_conteudo_ler() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.conteudo_ler_.Get();
}
inline void LeReply::_internal_set_conteudo_ler(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.conteudo_ler_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL LeReply::_internal_mutable_conteudo_ler() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.conteudo_ler_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE LeReply::release_conteudo_ler() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:sistemaarquivos.LeReply.conteudo_ler)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.conteudo_ler_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.conteudo_ler_.Set("", GetArena());
  }
  return released;
}
inline void LeReply::set_allocated_conteudo_ler(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.conteudo_ler_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.conteudo_ler_.IsDefault()) {
    _impl_.conteudo_ler_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:sistemaarquivos.LeReply.conteudo_ler)
}

// -------------------------------------------------------------------

// EscreveRequest

// int32 descritor = 1;
inline void EscreveRequest::clear_descritor() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.descritor_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t EscreveRequest::descritor() const {
  // @@protoc_insertion_point(field_get:sistemaarquivos.EscreveRequest.descritor)
  return _internal_descritor();
}
inline void EscreveRequest::set_descritor(::int32_t value) {
  _internal_set_descritor(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:sistemaarquivos.EscreveRequest.descritor)
}
inline ::int32_t EscreveRequest::_internal_descritor() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.descritor_;
}
inline void EscreveRequest::_internal_set_descritor(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.descritor_ = value;
}

// int32 posicao = 2;
inline void EscreveRequest::clear_posicao() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.posicao_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t EscreveRequest::posicao() const {
  // @@protoc_insertion_point(field_get:sistemaarquivos.EscreveRequest.posicao)
  return _internal_posicao();
}
inline void EscreveRequest::set_posicao(::int32_t value) {
  _internal_set_posicao(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:sistemaarquivos.EscreveRequest.posicao)
}
inline ::int32_t EscreveRequest::_internal_posicao() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.posicao_;
}
inline void EscreveRequest::_internal_set_posicao(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.posicao_ = value;
}

// bytes conteudo_escrever = 3;
inline void EscreveRequest::clear_conteudo_escrever() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.conteudo_escrever_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& EscreveRequest::conteudo_escrever() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:sistemaarquivos.EscreveRequest.conteudo_escrever)
  return _internal_conteudo_escrever();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void EscreveRequest::set_conteudo_escrever(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.conteudo_escrever_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:sistemaarquivos.EscreveRequest.conteudo_escrever)
}
inline ::std::string* PROTOBUF_NONNULL EscreveRequest::mutable_conteudo_escrever()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_conteudo_escrever();
  // @@protoc_insertion_point(field_mutable:sistemaarquivos.EscreveRequest.conteudo_escrever)
  return _s;
}
inline const ::std::string& EscreveRequest::_internal_conteudo_escrever() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.conteudo_escrever_.Get();
}
inline void EscreveRequest::_internal_set_conteudo_escrever(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.conteudo_escrever_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL EscreveRequest::_internal_mutable_conteudo_escrever() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.conteudo_escrever_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE EscreveRequest::release_conteudo_escrever() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:sistemaarquivos.EscreveRequest.conteudo_escrever)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.conteudo_escrever_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.conteudo_escrever_.Set("", GetArena());
  }
  return released;
}
inline void EscreveRequest::set_allocated_conteudo_escrever(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.conteudo_escrever_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.conteudo_escrever_.IsDefault()) {
    _impl_.conteudo_escrever_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:sistemaarquivos.EscreveRequest.conteudo_escrever)
}

// -------------------------------------------------------------------

// EscreveReply

// int32 status = 1;
inline void EscreveReply::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t EscreveReply::status() const {
  // @@protoc_insertion_point(field_get:sistemaarquivos.EscreveReply.status)
  return _internal_status();
}
inline void EscreveReply::set_status(::int32_t value) {
  _internal_set_status(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:sistemaarquivos.EscreveReply.status)
}
inline ::int32_t EscreveReply::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.status_;
}
inline void EscreveReply::_internal_set_status(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

// int32 bytes_escritos = 2;
inline void EscreveReply::clear_bytes_escritos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bytes_escritos_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t EscreveReply::bytes_escritos() const {
  // @@protoc_insertion_point(field_get:sistemaarquivos.EscreveReply.bytes_escritos)
  return _internal_bytes_escritos();
}
inline void EscreveReply::set_bytes_escritos(::int32_t value) {
  _internal_set_bytes_escritos(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:sistemaarquivos.EscreveReply.bytes_escritos)
}
inline ::int32_t EscreveReply::_internal_bytes_escritos() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bytes_escritos_;
}
inline void EscreveReply::_internal_set_bytes_escritos(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bytes_escritos_ = value;
}

// -------------------------------------------------------------------

// FechaRequest

// int32 descritor = 1;
inline void FechaRequest::clear_descritor() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.descritor_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t FechaRequest::descritor() const {
  // @@protoc_insertion_point(field_get:sistemaarquivos.FechaRequest.descritor)
  return _internal_descritor();
}
inline void FechaRequest::set_descritor(::int32_t value) {
  _internal_set_descritor(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:sistemaarquivos.FechaRequest.descritor)
}
inline ::int32_t FechaRequest::_internal_descritor() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.descritor_;
}
inline void FechaRequest::_internal_set_descritor(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.descritor_ = value;
}

// -------------------------------------------------------------------

// FechaReply

// int32 status = 1;
inline void FechaReply::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t FechaReply::status() const {
  // @@protoc_insertion_point(field_get:sistemaarquivos.FechaReply.status)
  return _internal_status();
}
inline void FechaReply::set_status(::int32_t value) {
  _internal_set_status(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:sistemaarquivos.FechaReply.status)
}
inline ::int32_t FechaReply::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.status_;
}
inline void FechaReply::_internal_set_status(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace sistemaarquivos


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // sistema_5farquivos_2eproto_2epb_2eh
