// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: sistema_arquivos.proto

package sistemaarquivos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AbreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NomeArquivo   string                 `protobuf:"bytes,1,opt,name=nome_arquivo,json=nomeArquivo,proto3" json:"nome_arquivo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbreRequest) Reset() {
	*x = AbreRequest{}
	mi := &file_sistema_arquivos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbreRequest) ProtoMessage() {}

func (x *AbreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_arquivos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbreRequest.ProtoReflect.Descriptor instead.
func (*AbreRequest) Descriptor() ([]byte, []int) {
	return file_sistema_arquivos_proto_rawDescGZIP(), []int{0}
}

func (x *AbreRequest) GetNomeArquivo() string {
	if x != nil {
		return x.NomeArquivo
	}
	return ""
}

type AbreReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Descritor     int32                  `protobuf:"varint,2,opt,name=descritor,proto3" json:"descritor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbreReply) Reset() {
	*x = AbreReply{}
	mi := &file_sistema_arquivos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbreReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbreReply) ProtoMessage() {}

func (x *AbreReply) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_arquivos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbreReply.ProtoReflect.Descriptor instead.
func (*AbreReply) Descriptor() ([]byte, []int) {
	return file_sistema_arquivos_proto_rawDescGZIP(), []int{1}
}

func (x *AbreReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AbreReply) GetDescritor() int32 {
	if x != nil {
		return x.Descritor
	}
	return 0
}

type LeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Descritor     int32                  `protobuf:"varint,1,opt,name=descritor,proto3" json:"descritor,omitempty"`
	Posicao       int32                  `protobuf:"varint,2,opt,name=posicao,proto3" json:"posicao,omitempty"`
	Tamanho       int32                  `protobuf:"varint,3,opt,name=tamanho,proto3" json:"tamanho,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeRequest) Reset() {
	*x = LeRequest{}
	mi := &file_sistema_arquivos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeRequest) ProtoMessage() {}

func (x *LeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_arquivos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeRequest.ProtoReflect.Descriptor instead.
func (*LeRequest) Descriptor() ([]byte, []int) {
	return file_sistema_arquivos_proto_rawDescGZIP(), []int{2}
}

func (x *LeRequest) GetDescritor() int32 {
	if x != nil {
		return x.Descritor
	}
	return 0
}

func (x *LeRequest) GetPosicao() int32 {
	if x != nil {
		return x.Posicao
	}
	return 0
}

func (x *LeRequest) GetTamanho() int32 {
	if x != nil {
		return x.Tamanho
	}
	return 0
}

type LeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	ConteudoLer   []byte                 `protobuf:"bytes,2,opt,name=conteudo_ler,json=conteudoLer,proto3" json:"conteudo_ler,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeReply) Reset() {
	*x = LeReply{}
	mi := &file_sistema_arquivos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeReply) ProtoMessage() {}

func (x *LeReply) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_arquivos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeReply.ProtoReflect.Descriptor instead.
func (*LeReply) Descriptor() ([]byte, []int) {
	return file_sistema_arquivos_proto_rawDescGZIP(), []int{3}
}

func (x *LeReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LeReply) GetConteudoLer() []byte {
	if x != nil {
		return x.ConteudoLer
	}
	return nil
}

type EscreveRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Descritor        int32                  `protobuf:"varint,1,opt,name=descritor,proto3" json:"descritor,omitempty"`
	Posicao          int32                  `protobuf:"varint,2,opt,name=posicao,proto3" json:"posicao,omitempty"`
	ConteudoEscrever []byte                 `protobuf:"bytes,3,opt,name=conteudo_escrever,json=conteudoEscrever,proto3" json:"conteudo_escrever,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EscreveRequest) Reset() {
	*x = EscreveRequest{}
	mi := &file_sistema_arquivos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscreveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscreveRequest) ProtoMessage() {}

func (x *EscreveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_arquivos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscreveRequest.ProtoReflect.Descriptor instead.
func (*EscreveRequest) Descriptor() ([]byte, []int) {
	return file_sistema_arquivos_proto_rawDescGZIP(), []int{4}
}

func (x *EscreveRequest) GetDescritor() int32 {
	if x != nil {
		return x.Descritor
	}
	return 0
}

func (x *EscreveRequest) GetPosicao() int32 {
	if x != nil {
		return x.Posicao
	}
	return 0
}

func (x *EscreveRequest) GetConteudoEscrever() []byte {
	if x != nil {
		return x.ConteudoEscrever
	}
	return nil
}

type EscreveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	BytesEscritos int32                  `protobuf:"varint,2,opt,name=bytes_escritos,json=bytesEscritos,proto3" json:"bytes_escritos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EscreveReply) Reset() {
	*x = EscreveReply{}
	mi := &file_sistema_arquivos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscreveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscreveReply) ProtoMessage() {}

func (x *EscreveReply) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_arquivos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscreveReply.ProtoReflect.Descriptor instead.
func (*EscreveReply) Descriptor() ([]byte, []int) {
	return file_sistema_arquivos_proto_rawDescGZIP(), []int{5}
}

func (x *EscreveReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *EscreveReply) GetBytesEscritos() int32 {
	if x != nil {
		return x.BytesEscritos
	}
	return 0
}

type FechaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Descritor     int32                  `protobuf:"varint,1,opt,name=descritor,proto3" json:"descritor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FechaRequest) Reset() {
	*x = FechaRequest{}
	mi := &file_sistema_arquivos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FechaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FechaRequest) ProtoMessage() {}

func (x *FechaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_arquivos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FechaRequest.ProtoReflect.Descriptor instead.
func (*FechaRequest) Descriptor() ([]byte, []int) {
	return file_sistema_arquivos_proto_rawDescGZIP(), []int{6}
}

func (x *FechaRequest) GetDescritor() int32 {
	if x != nil {
		return x.Descritor
	}
	return 0
}

type FechaReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FechaReply) Reset() {
	*x = FechaReply{}
	mi := &file_sistema_arquivos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FechaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FechaReply) ProtoMessage() {}

func (x *FechaReply) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_arquivos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FechaReply.ProtoReflect.Descriptor instead.
func (*FechaReply) Descriptor() ([]byte, []int) {
	return file_sistema_arquivos_proto_rawDescGZIP(), []int{7}
}

func (x *FechaReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_sistema_arquivos_proto protoreflect.FileDescriptor

const file_sistema_arquivos_proto_rawDesc = "" +
	"\n" +
	"\x16sistema_arquivos.proto\x12\x0fsistemaarquivos\"0\n" +
	"\vAbreRequest\x12!\n" +
	"\fnome_arquivo\x18\x01 \x01(\tR\vnomeArquivo\"A\n" +
	"\tAbreReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x1c\n" +
	"\tdescritor\x18\x02 \x01(\x05R\tdescritor\"]\n" +
	"\tLeRequest\x12\x1c\n" +
	"\tdescritor\x18\x01 \x01(\x05R\tdescritor\x12\x18\n" +
	"\aposicao\x18\x02 \x01(\x05R\aposicao\x12\x18\n" +
	"\atamanho\x18\x03 \x01(\x05R\atamanho\"D\n" +
	"\aLeReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12!\n" +
	"\fconteudo_ler\x18\x02 \x01(\fR\vconteudoLer\"u\n" +
	"\x0eEscreveRequest\x12\x1c\n" +
	"\tdescritor\x18\x01 \x01(\x05R\tdescritor\x12\x18\n" +
	"\aposicao\x18\x02 \x01(\x05R\aposicao\x12+\n" +
	"\x11conteudo_escrever\x18\x03 \x01(\fR\x10conteudoEscrever\"M\n" +
	"\fEscreveReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12%\n" +
	"\x0ebytes_escritos\x18\x02 \x01(\x05R\rbytesEscritos\",\n" +
	"\fFechaRequest\x12\x1c\n" +
	"\tdescritor\x18\x01 \x01(\x05R\tdescritor\"$\n" +
	"\n" +
	"FechaReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status2\x9f\x02\n" +
	"\x0fSistemaArquivos\x12@\n" +
	"\x04Abre\x12\x1c.sistemaarquivos.AbreRequest\x1a\x1a.sistemaarquivos.AbreReply\x12:\n" +
	"\x02Le\x12\x1a.sistemaarquivos.LeRequest\x1a\x18.sistemaarquivos.LeReply\x12I\n" +
	"\aEscreve\x12\x1f.sistemaarquivos.EscreveRequest\x1a\x1d.sistemaarquivos.EscreveReply\x12C\n" +
	"\x05Fecha\x12\x1d.sistemaarquivos.FechaRequest\x1a\x1b.sistemaarquivos.FechaReplyBE\n" +
	"\x15com.mycompany.ine5418B\x14SistemaArquivosProtoZ\x16/proto;sistemaarquivosb\x06proto3"

var (
	file_sistema_arquivos_proto_rawDescOnce sync.Once
	file_sistema_arquivos_proto_rawDescData []byte
)

func file_sistema_arquivos_proto_rawDescGZIP() []byte {
	file_sistema_arquivos_proto_rawDescOnce.Do(func() {
		file_sistema_arquivos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sistema_arquivos_proto_rawDesc), len(file_sistema_arquivos_proto_rawDesc)))
	})
	return file_sistema_arquivos_proto_rawDescData
}

var file_sistema_arquivos_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sistema_arquivos_proto_goTypes = []any{
	(*AbreRequest)(nil),    // 0: sistemaarquivos.AbreRequest
	(*AbreReply)(nil),      // 1: sistemaarquivos.AbreReply
	(*LeRequest)(nil),      // 2: sistemaarquivos.LeRequest
	(*LeReply)(nil),        // 3: sistemaarquivos.LeReply
	(*EscreveRequest)(nil), // 4: sistemaarquivos.EscreveRequest
	(*EscreveReply)(nil),   // 5: sistemaarquivos.EscreveReply
	(*FechaRequest)(nil),   // 6: sistemaarquivos.FechaRequest
	(*FechaReply)(nil),     // 7: sistemaarquivos.FechaReply
}
var file_sistema_arquivos_proto_depIdxs = []int32{
	0, // 0: sistemaarquivos.SistemaArquivos.Abre:input_type -> sistemaarquivos.AbreRequest
	2, // 1: sistemaarquivos.SistemaArquivos.Le:input_type -> sistemaarquivos.LeRequest
	4, // 2: sistemaarquivos.SistemaArquivos.Escreve:input_type -> sistemaarquivos.EscreveRequest
	6, // 3: sistemaarquivos.SistemaArquivos.Fecha:input_type -> sistemaarquivos.FechaRequest
	1, // 4: sistemaarquivos.SistemaArquivos.Abre:output_type -> sistemaarquivos.AbreReply
	3, // 5: sistemaarquivos.SistemaArquivos.Le:output_type -> sistemaarquivos.LeReply
	5, // 6: sistemaarquivos.SistemaArquivos.Escreve:output_type -> sistemaarquivos.EscreveReply
	7, // 7: sistemaarquivos.SistemaArquivos.Fecha:output_type -> sistemaarquivos.FechaReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sistema_arquivos_proto_init() }
func file_sistema_arquivos_proto_init() {
	if File_sistema_arquivos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sistema_arquivos_proto_rawDesc), len(file_sistema_arquivos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sistema_arquivos_proto_goTypes,
		DependencyIndexes: file_sistema_arquivos_proto_depIdxs,
		MessageInfos:      file_sistema_arquivos_proto_msgTypes,
	}.Build()
	File_sistema_arquivos_proto = out.File
	file_sistema_arquivos_proto_goTypes = nil
	file_sistema_arquivos_proto_depIdxs = nil
}
